apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: node-role.kubernetes.io/acm=true
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "node-role.kubernetes.io/acm",
      "Operator": "Equal", "Value": "true", "Effect": "NoExecute"}]'
  name: open-cluster-management
  labels:
    kubernetes.io/metadata.name: open-cluster-management
spec:
  finalizers:
  - kubernetes
